services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3308:3306"
    volumes:
      - auth-mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  auth-mysql-data: